In [2]:
# Dependencies and Setup
import csv
import pandas as pd
import os
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress 
import seaborn as sns 
from scipy import stats

In [4]:
zillow_file = '../Data/Zillow_AllHomes_5yrs_Clean.csv'
zillow_df = pd.read_csv(zillow_file)
zillow_df

,RegionName,StateName,SizeRank,RegionID,RegionType,1/31/2015,2/28/2015,3/31/2015,4/30/2015,5/31/2015,...,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020,6/30/2020,7/31/2020,8/31/2020,9/30/2020,10/31/2020
0,United States,NaN,0,102001,Country,190722.0,191467.0,192335.0,193235.0,194147.0,...,248440,249439,250595,251849,253057,254320,255845,257804,260091,262604
1,"New York, NY",NY,1,394913,Msa,408905.0,410065.0,410802.0,411779.0,412581.0,...,483191,484139,485177,486507,488000,489895,492468,495908,500412,505569
2,"Los Angeles-Long Beach-Anaheim, CA",CA,2,753899,Msa,526530.0,530547.0,534737.0,537106.0,539643.0,...,680279,685435,690691,695044,696786,698190,702883,710534,718779,726379
3,"Chicago, IL",IL,3,394463,Msa,206017.0,206142.0,206800.0,207924.0,208932.0,...,244738,245092,245678,246204,246794,247545,248846,250588,252917,255532
4,"Dallas-Fort Worth, TX",TX,4,394514,Msa,177328.0,178799.0,180484.0,182120.0,183830.0,...,258147,258784,259781,260955,262153,263579,265256,267187,269202,271831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909,"Lamesa, TX",TX,929,394767,Msa,53736.0,53906.0,54068.0,54405.0,54750.0,...,75464,75574,75675,75855,76098,76387,76621,76858,77100,77318
910,"Craig, CO",CO,930,753874,Msa,164710.0,166051.0,167511.0,168959.0,170713.0,...,187904,187767,187773,187876,187968,188152,188263,188376,188477,188683
911,"Pecos, TX",TX,931,394968,Msa,NaN,NaN,NaN,NaN,NaN,...,129050,130440,131600,131928,132350,132891,133018,132368,130725,128486
912,"Vernon, TX",TX,932,395188,Msa,56866.0,57187.0,57451.0,57682.0,58006.0,...,70018,69886,69751,69660,69645,69578,69558,69536,69554,69449
913,"Ketchikan, AK",AK,933,394743,Msa,275225.0,276036.0,276588.0,277246.0,277891.0,...,311124,311199,311318,311267,311349,311348,311501,311934,312375,313013

In [6]:
homeless_file = '../Data/2015-2019_PITbyState_ChangeHomelessness_Clean.csv'
homeless_df = pd.read_csv(homeless_file)
homeless_df

,State,"Change in Total Homelessness, 2018-2019","Change in Total Homelessness, 2017-2019","Change in Total Homelessness, 2016-2019","Change in Total Homelessness, 2015-2019"
0,AK,-5.40%,3.40%,-1.70%,-2.50%
1,AL,-5.00%,-14.00%,-20.70%,-17.90%
2,AR,0.20%,10.10%,10.30%,6.10%
3,AZ,1.40%,11.80%,3.10%,1.10%
4,CA,16.40%,15.00%,28.00%,30.70%
5,CO,-11.40%,-12.10%,-8.80%,-3.40%
6,CT,-23.70%,-10.50%,-22.30%,-25.10%
7,DC,-5.50%,-12.70%,-21.90%,-10.60%
8,DE,-14.90%,-7.30%,-13.90%,-3.40%
9,FL,-8.70%,-12.00%,-15.60%,-21.10%
10,GA,9.90%,2.60%,-19.10%,-24.30%
11,GU,2.50%,2.70%,-19.40%,-31.60%
12,HI,-1.80%,-11.20%,-19.10%,-15.90%
13,IA,-15.80%,-16.00%,-24.40%,-24.90%
14,ID,15.10%,13.60%,3.00%,17.80%
15,IL,-4.20%,-5.50%,-12.00%,-22.60%
16,IN,4.10%,0.60%,-5.60%,-6.70%
17,KS,7.40%,4.10%,5.60%,-8.00%
18,KY,10.60%,1.30%,-3.70%,-10.10%
19,LA,-3.90%,-11.00%,-26.40%,-27.90%
20,MA,-8.00%,5.20%,-5.80%,-12.60%
21,MD,-8.20%,-9.50%,-14.70%,-21.80%
22,ME,-16.30%,-7.60%,-6.00%,-11.20%
23,MI,2.70%,-5.30%,-8.00%,-18.50%
24,MN,10.10%,4.00%,8.70%,5.70%
25,MO,5.00%,2.40%,-0.20%,-4.70%
26,MP,73.10%,168.90%,,
27,MS,-12.40%,-19.60%,-31.90%,-40.30%
28,MT,-3.40%,-11.20%,-4.30%,-20.60%
29,NC,0.50%,3.90%,-2.60%,-12.80%
30,ND,2.80%,-48.90%,-39.70%,-57.30%
31,NE,-2.30%,-5.40%,-14.10%,-13.80%
32,NH,-3.70%,-4.10%,2.20%,-3.40%
33,NJ,-5.70%,3.80%,-0.40%,-12.20%
34,NM,27.00%,30.60%,43.20%,23.30%
35,NV,-5.00%,-8.50%,-3.10%,-18.00%
36,NY,0.20%,2.90%,6.60%,4.40%
37,OH,0.90%,2.50%,-0.60%,-7.50%
38,OK,1.90%,-6.10%,-4.00%,4.40%
39,OR,9.70%,13.80%,19.90%,20.00%
40,PA,-2.30%,-6.60%,-14.00%,-14.40%
41,PR,-20.30%,-28.10%,-42.60%,-43.90%
42,RI,-4.20%,-10.60%,-9.10%,-5.00%
43,SC,6.10%,6.50%,-17.40%,-22.10%
44,SD,-14.20%,5.50%,-7.20%,-4.00%
45,TN,-5.30%,-10.10%,-14.90%,-18.20%
46,TX,2.10%,9.80%,11.80%,9.20%
47,UT,-2.70%,-1.90%,-0.30%,-7.50%
48,VA,-3.20%,-4.70%,-7.70%,-17.40%
49,VI,-35.40%,-17.60%,-7.90%,-6.80%
50,VT,-15.60%,-11.10%,-2.50%,-28.50%
51,WA,-3.30%,2.20%,3.60%,11.10%
52,WI,-7.50%,-9.70%,-20.20%,-25.10%
53,WV,12.40%,6.70%,0.70%,-23.90%
54,WY,-14.20%,-37.20%,-36.10%,-31.30%
55,Total,2.70%,3.00%,3.20%,0.50%

In [7]:
gender_file = '../Data/HUD_DemoDataGender_5yrs_Clean.csv'
gender_df = pd.read_csv(gender_file)
gender_df

,Year,Gender,Emergency Shelter,Transitional Housing,Unsheltered,Total
0,2019.0,Female,"13,538","5,199","31,730","50,467"
1,2019.0,Male,"17,015","6,792","74,597","98,404"
2,2019.0,Transgender,128,108,"1,528","1,764"
3,2019.0,Gender Non-Conforming,42,24,577,643
4,2018.0,Female,"11,918","5,681","24,892","42,491"
5,2018.0,Male,"15,444","7,135","63,231","85,810"
6,2018.0,Transgender,87,128,"1,037","1,252"
7,2018.0,Gender Non-Conforming,26,10,383,419
8,2017.0,Female,"11,600","6,787","25,097","43,484"
9,2017.0,Male,"15,089","8,905","65,604","89,598"
10,2017.0,Transgender,142,79,576,797
11,2017.0,Gender Non-Conforming,23,11,365,399
12,2016.0,Female,"8,673","8,092","22,410","39,175"
13,2016.0,Male,"13,006","9,816","55,299","78,121"
14,2016.0,Transgender,87,78,681,846
15,2016.0,Gender Non-Conforming,0,0,0,0
16,2015.0,Female,"9,412","8,498","20,766","38,676"
17,2015.0,Male,"13,253","10,728","52,564","76,545"
18,2015.0,Transgender,85,63,369,517
19,2015.0,Gender Non-Conforming,0,0,0,0
20,NaN,NaN,"129,568","78,134","441,706","649,408"

In [33]:
# gender_df['Emergency Shelter'] = gender_df['Emergency Shelter'].str.replace(',','')
# gender_df['Emergency Shelter'] = gender_df['Emergency Shelter'].astype('float')
# gender_df['Transitional Housing'] = gender_df['Transitional Housing'].str.replace(',','')
# gender_df['Transitional Housing'] = gender_df['Transitional Housing'].astype('float')
gender_df['Unsheltered'] = gender_df['Unsheltered'].str.replace(',','')
gender_df['Unsheltered'] = gender_df['Unsheltered'].astype('float')
gender_df['Total'] = gender_df['Total'].str.replace(',','')
gender_df['Total'] = gender_df['Total'].astype('float')

In [34]:
gender_df.dtypes

Year                    float64
Gender                   object
Emergency Shelter       float64
Transitional Housing    float64
Unsheltered             float64
Total                   float64
dtype: object

In [35]:
gender_df.dropna(how='any', inplace=True)
gender_df.groupby('Year').sum()

        Emergency Shelter  Transitional Housing  Unsheltered     Total
Year
2015.0            22750.0               19289.0      73699.0  115738.0
2016.0            21766.0               17986.0      78390.0  118142.0
2017.0            26854.0               15782.0      91642.0  134278.0
2018.0            27475.0               12954.0      89543.0  129972.0
2019.0            30723.0               12123.0     108432.0  151278.0

In [25]:
race_file = '../Data/HUD_DemoDataRace_5yrs_Clean.csv'
race_df = pd.read_csv(race_file)
race_df.dtypes

Year                    float64
Race                     object
Emergency Shelter        object
Transitional Housing     object
Unsheltered              object
Total                    object
dtype: object

In [26]:
file_2019 = '../Data/2019_PIT_EstimatesHomelessness_Clean.csv'
f2019_df = pd.read_csv(file_2019)
f2019_df

,State,Number of CoCs,"Overall Homeless, 2019","Overall Homeless - Under 18, 2019","Overall Homeless - Age 18 to 24, 2019","Overall Homeless - Over 24, 2019","Overall Homeless - Female, 2019","Overall Homeless - Male, 2019","Overall Homeless - Transgender, 2019","Overall Homeless - Gender Non-Conforming, 2019",...,"Overall Homeless Parenting Youth Age 18-24, 2019","Sheltered ES Homeless Parenting Youth Age 18-24, 2019","Sheltered TH Homeless Parenting Youth Age 18-24, 2019","Sheltered Total Homeless Parenting Youth Age 18-24, 2019","Unsheltered Homeless Parenting Youth Age 18-24, 2019","Overall Homeless Children of Parenting Youth, 2019","Sheltered ES Homeless Children of Parenting Youth, 2019","Sheltered TH Homeless Children of Parenting Youth, 2019","Sheltered Total Homeless Children of Parenting Youth, 2019","Unsheltered Homeless Children of Parenting Youth, 2019"
0,AK,2.0,"1,907",335,204,"1,368",761,"1,137",6,3,...,20,6,14,20,0.0,27,13,14,27,0.0
1,AL,8.0,"3,261",629,199,"2,433","1,383","1,873",3,2,...,22,10,11,21,1.0,34,17,13,30,4.0
2,AR,5.0,"2,717",303,317,"2,097","1,022","1,688",4,3,...,11,7,4,11,0.0,15,10,5,15,0.0
3,AZ,3.0,"10,007","1,602",708,"7,697","3,683","6,297",16,11,...,58,17,40,57,1.0,80,26,53,79,1.0
4,CA,44.0,"151,278","14,305","12,673","124,300","50,467","98,404","1,764",643,...,"1,019",457,291,748,271.0,"1,194",555,357,912,282.0
5,CO,3.0,"9,619","1,458",685,"7,476","3,238","6,289",54,38,...,80,19,59,78,2.0,111,21,83,104,7.0
6,CT,2.0,"3,033",588,272,"2,173","1,133","1,895",4,1,...,58,25,31,56,2.0,81,36,42,78,3.0
7,DC,1.0,"6,521","1,606",546,"4,369","2,649","3,823",40,9,...,214,116,98,214,0.0,272,151,121,272,0.0
8,DE,1.0,921,220,83,618,373,546,1,1,...,16,10,5,15,1.0,21,14,6,20,1.0
9,FL,27.0,"28,328","4,703","1,625","22,000","9,884","18,357",67,20,...,253,140,91,231,22.0,419,228,158,386,33.0
10,GA,9.0,"10,443","1,679",642,"8,122","3,765","6,610",57,11,...,88,40,44,84,4.0,105,57,44,101,4.0
11,GU,1.0,875,334,95,446,427,448,0,0,...,8,2,1,3,5.0,11,2,3,5,6.0
12,HI,2.0,"6,412","1,177",323,"4,912","2,591","3,778",37,6,...,55,19,25,44,11.0,47,10,29,39,8.0
13,IA,3.0,"2,315",495,187,"1,633",917,"1,395",2,1,...,42,17,25,42,0.0,52,25,27,52,0.0
14,ID,2.0,"2,315",473,220,"1,622",920,"1,392",0,3,...,19,12,4,16,3.0,29,18,8,26,3.0
15,IL,19.0,"10,199","2,355",926,"6,918","4,241","5,914",31,13,...,241,91,144,235,6.0,351,152,191,343,8.0
16,IN,2.0,"5,471","1,092",327,"4,052","2,205","3,246",15,5,...,58,44,11,55,3.0,85,63,19,82,3.0
17,KS,5.0,"2,381",383,150,"1,848",932,"1,445",1,3,...,17,9,8,17,0.0,24,12,12,24,0.0
18,KY,3.0,"4,079",629,308,"3,142","1,584","2,492",3,0,...,41,27,12,39,2.0,61,38,20,58,3.0
19,LA,7.0,"2,941",375,182,"2,384",867,"2,058",9,7,...,25,17,8,25,0.0,34,23,11,34,0.0
20,MA,15.0,"18,471","7,357","1,540","9,574","9,118","9,311",28,14,...,476,438,37,475,1.0,573,520,52,572,1.0
21,MD,16.0,"6,561","1,214",399,"4,948","2,490","4,047",22,2,...,78,42,33,75,3.0,100,50,48,98,2.0
22,ME,1.0,"2,106",541,147,"1,418",995,"1,094",13,4,...,16,7,9,16,0.0,19,8,11,19,0.0
23,MI,21.0,"8,575","2,231",712,"5,632","3,532","5,026",13,4,...,202,111,89,200,2.0,351,218,132,350,1.0
24,MN,10.0,"7,977","2,157",900,"4,920","3,554","4,385",29,9,...,171,61,103,164,7.0,231,83,138,221,10.0
25,MO,8.0,"6,179","1,359",545,"4,275","2,696","3,451",20,12,...,125,47,73,120,5.0,185,82,97,179,6.0
26,MP,1.0,"1,807",586,191,"1,030",837,970,0,0,...,1,1,0,1,0.0,1,1,0,1,0.0
27,MS,3.0,"1,184",152,55,977,417,752,0,15,...,4,3,1,4,0.0,5,4,1,5,0.0
28,MT,1.0,"1,357",250,111,996,555,793,4,5,...,19,8,11,19,0.0,32,17,15,32,0.0
29,NC,12.0,"9,314","1,553",532,"7,229","3,576","5,716",12,10,...,56,40,10,50,6.0,80,59,16,75,5.0
30,ND,1.0,557,127,74,356,178,378,1,0,...,5,3,2,5,0.0,4,2,2,4,0.0
31,NE,3.0,"2,365",423,185,"1,757",866,"1,494",4,1,...,27,13,14,27,0.0,40,18,22,40,0.0
32,NH,3.0,"1,396",352,117,927,626,758,3,9,...,24,13,10,23,1.0,36,21,14,35,1.0
33,NJ,16.0,"8,862","1,831",714,"6,317","3,579","5,264",17,2,...,178,125,52,177,1.0,240,179,60,239,1.0
34,NM,2.0,"3,241",515,217,"2,509","1,278","1,930",19,14,...,23,7,14,21,2.0,26,8,15,23,3.0
35,NV,3.0,"7,169",656,"1,025","5,488","2,095","5,042",31,1,...,43,12,15,27,16.0,45,15,18,33,12.0
36,NY,27.0,"92,091","28,985","8,444","54,662","42,980","48,685",401,25,...,"2,448","2,402",44,"2,446",2.0,"2,998","2,936",61,"2,997",1.0
37,OH,9.0,"10,345","2,135",853,"7,357","4,131","6,185",26,3,...,165,111,51,162,3.0,243,173,68,241,2.0
38,OK,8.0,"3,944",549,327,"3,068","1,351","2,578",7,8,...,44,17,16,33,11.0,53,21,15,36,17.0
39,OR,7.0,"15,876","2,645","1,116","12,115","6,187","9,551",77,61,...,103,15,43,58,45.0,110,19,43,62,48.0
40,PA,16.0,"13,199","3,020","1,079","9,100","5,373","7,776",32,18,...,283,130,150,280,3.0,407,187,217,404,3.0
41,PR,2.0,"2,535",110,85,"2,340",533,"1,990",11,1,...,12,3,8,11,1.0,18,5,11,16,2.0
42,RI,1.0,"1,055",197,39,819,358,690,7,0,...,4,2,2,4,0.0,3,2,1,3,0.0
43,SC,4.0,"4,172",520,263,"3,389","1,520","2,647",2,3,...,32,11,13,24,8.0,39,12,18,30,9.0
44,SD,1.0,995,188,72,735,389,605,1,0,...,8,7,1,8,0.0,13,10,3,13,0.0
45,TN,10.0,"7,467","1,170",421,"5,876","2,823","4,632",10,2,...,49,14,11,25,24.0,74,15,14,29,45.0
46,TX,11.0,"25,848","4,249","1,523","20,076","9,404","16,361",66,17,...,184,112,62,174,10.0,280,170,96,266,14.0
47,UT,3.0,"2,798",565,190,"2,043","1,108","1,673",12,5,...,19,16,3,19,0.0,28,23,5,28,0.0
48,VA,16.0,"5,783","1,346",367,"4,070","2,318","3,452",9,4,...,74,52,21,73,1.0,102,76,25,101,1.0
49,VI,1.0,314,0,6,308,73,236,0,5,...,0,0,0,0,0.0,0,0,0,0,0.0
50,VT,2.0,"1,089",251,136,702,461,616,9,3,...,27,22,4,26,1.0,35,30,4,34,1.0
51,WA,6.0,"21,577","3,557","2,123","15,897","8,820","12,190",246,321,...,173,69,92,161,12.0,225,97,112,209,16.0
52,WI,4.0,"4,538","1,303",286,"2,949","1,947","2,578",9,4,...,73,44,28,72,1.0,115,71,43,114,1.0
53,WV,4.0,"1,397",153,94,"1,150",529,868,0,0,...,10,7,2,9,1.0,11,7,2,9,2.0
54,WY,1.0,548,81,69,398,172,376,0,0,...,4,2,2,4,0.0,4,2,2,4,0.0
55,Total,397.0,"567,715","107,069","45,629","415,017","219,911","343,187","3,255","1,362",...,"7,505","5,052","1,952","7,004",501.0,"9,779","6,612","2,597","9,209",570.0
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN